### ISSUE TITLE
Menu item text normalization

### ISSUE THREAD

**Issue by asfalcone** [Droidcon-Boston/conference-app-android#11]
Menu item text is all over the place:

```
Open Twitter
Our Facebook
Instagram Too
```
Something more uniform and simple would be better
```
Twitter
Facebook
Instagram
```

**Comment by emezias** [comment]
The menu items you want to change are all all over the place because they
are external links. It's a simple list without sections. That section is
the Contact Us piece. There is overlap with an in-app Twitter fragment and
a link to open Twitter to Droidcon Boston. How do you want to handle that?

On Apr 3, 2017 9:33 PM, "Andrea Falcone" <notifications@github.com> wrote:

Menu item text is all over the place:

Open Twitter
Our Facebook
Instagram Too

Something more uniform and simple would be better

Twitter
Facebook
Instagram

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Droidcon-Boston/conference-app-android/issues/11>, or mute
the thread

**Comment by emezias** [comment]
The contact icons are now highlighted with a green background that is intended to indicate that tapping such items will leave the app
