### ISSUE TITLE
User Profile + Sharing

### ISSUE THREAD

**Issue by n8ebel** [Droidcon-Boston/conference-app-android#131]
Allow a user to have their own conference profile, and allow attendees to connect with one another and share info via the app

**Comment by n8ebel** [comment]
ideas from last year's discussion of this idea:

Customizable user profile for job title, tagline, social handles, links of interest.

Possible integrations:

- Chat (Click on user to view profile)
- One-to-one sharing: QR code, NFC/Beam tap, etc to transfer contact card to other users
    - This kind of contact sharing is already present in Android's contacts app, but we can provide something conference-specific, with the ability to save shared profiles to contacts
- Possibility of some sort of "check in" for talks, where users can choose to publicly share their presence, other users can see who attended a talk afterwards

**Comment by GiorgioNatili** [comment]
Profile can be generated using the Eventbrite ticket QR code and get the information that the user already shared with the conference (email, twitter handle, city/country). Optionally, the user can add more social media links and a short profile.

**Comment by CCorrado** [comment]
Some high-level notes:
- We want to be able to get the "attendee" data from Eventbrite so that the user can link the data from their ticket purchase to Droidcon Boston 2019.
- The EB API doesn't really have an easy way to do this. I cannot simply authenticate myself and retrieve my own **attendee** data for an event via the API. Any of us can, however, authenticate ourselves via OAuth and retrieve our Eventbrite Profiles which simply contains our name, email, and Image ID.
 
For integrating with Eventbrite: 
0. We'll need the organizer to set up an app in the EB API Apps section. This is needed so that we can retrieve a list of attendees to the DC Boston 2019 Event (ID: 51797973132) 
- URL to configure an App in EB as an Organizer: https://www.eventbrite.com/myaccount/apps/
- It probably makes sense to do these queries on the backend rather than on the user's phone.

1. We can have a list of all attendees for the event via this API: https://www.eventbriteapi.com/v3/events/51797973132/attendees/
(DOCS: https://www.eventbrite.com/platform/api/#/reference/attendee/list/list-attendees-by-event)
- This list contains all attendees, so again it makes more sense to keep this on the backend so that the client doesn't ever intercept this information.
- We'll have to have the user authenticate the app with EB via their OAuth portal. DOCS: https://www.eventbrite.com/platform/api/#/introduction/authentication/getting-a-token

2. Once the user is authenticated via OAuth, then we can use their e-mail from their profile to do a lookup on the list of attendees that we previously queried on the backend and retrieve their relevant EB/Attendee information. 


If the user doesn't opt-in to linking their ticket via Eventbrite, we can just simply make a registration form that creates a User object in the DC Boston backend/datastore containing their name, email, and additionally (optionally) social media links. (Twitter, Instagram, LinkedIn etc)

**Comment by CCorrado** [comment]
Story description: As an attendee, I want to optionally register with Droidcon Boston so that I may engage with other attendees and sync my agenda.

AC#1: The app should work as it does today, without a user profile. It should be optional for the user to register.
AC#2: Registration should be made available to the user as a menu option in a separate area of the app. 
AC#3: Registration will require the users full name and valid e-mail address (preferably the one they used to buy their conference ticket with). 
AC#4: Registration will optionally allow the user to add social media links (Twitter, LinkedIn, etc)
AC#5: Eventbrite SSO is made available to the user and should create a profile with Droidcon Boston and pull ONLY the following:
- full name
- username
- EB profile image
- e-mail
- linked social media
AC#6: The user should be able to view their profile details in the app.
AC#7: The user should be able to unregister and have their data removed from the Droidcon Boston backend system at any time.
AC#8: If the user unregisters, any data they have locally to their phone should NOT be deleted.

**Comment by GiorgioNatili** [comment]
I shared the app keys with you on Slack.

**Comment by n8ebel** [comment]
@CCorrado   How is this ticket coming?  Are you still waiting on a final review for the PR that is open?

**Comment by CCorrado** [comment]
Hey @n8ebel yeah, the open PR should get merged so that the team can use that Profile object to associate the user with the app. It is done functionally...I need to resolve conflicts...probably from this past Sundays changes.

**Comment by CCorrado** [comment]
@n8ebel  @GiorgioNatili  I updated the PR #136, looks like all the checks are passing. Let me know if I can merge!

**Comment by n8ebel** [comment]
@CCorrado   Can we consider this issue closed?  or is there more to go that builds upon #136 ?

**Comment by CCorrado** [comment]
Let's close this one out, users can sign in and profiles can be created and sync'd I think that's good for MVP. @n8ebel
