### ISSUE TITLE
A couple of the FB and LI profile links aren't working

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#22]
Sam Edwards - clicking on the "In" LinkedIn icon in the profile seems to open a browser to somewhere else and then open LinkedIn. Every other profile goes straight to LinkedIn. Is there something different about this link from the other speaker bios?

Jason Sendros-Keshka  -- Facebook page is not linking to his page

Andres Colubri - Facebook page is not linking to his page. I just went back to my email where he sent me his Facebook URL but I see it also doesn't work:  https://www.facebook.com/andres.colubri  I can ask him to confirm if we have time to fix it?

**Comment by emezias** [comment]
When corrected links are provided, we can fix this on Android easily. IOS is submitted.

It would seem that Facebook has not 'registered' it's web site so that deep links will automatically open in the app on newer Androids. Future releases might add logic to look for installed apps instead of trying the action view type of Intent to open the link.

**Comment by emezias** [comment]
Revised the links mentioned in this issue. Andres has no social links

**Comment by fetching** [comment]
Thanks Elizabeth!  I see the issue for Facebook is that I do not have the Facebook app installed on my phone.  I just uninstalled Twitter and LinkedIn apps and get the same behavior for non-public profiles. 

Can we restore their Facebook profile URLs so that they will work for folks who do have Facebook app installed?  Apologies for the confusion.

**Comment by emezias** [comment]
@fetching I made a mistake - Andres has a Twitter link. HIs Facebook got removed because it didn't work on my desktop (but now it does). That's the only change I made. The other two speakers' links got verified and are definitely working in the app on the store. When we post an app update, a new apk, I will make sure it has a new db file with Andres Facebook.

**Comment by fetching** [comment]
Terrific Elizabeth, you rock!  (My guess is your desktop browser is logged in to Facebook so it works now.)

**Comment by emezias** [comment]
It has to work though, logged in or not. Seriously, it wasn't the standard
'login to see more' message. If Andres privacy settings are such that the
app might open an error page I would prefer not to push that link.

On Apr 6, 2017 11:29 PM, "fetching" <notifications@github.com> wrote:

Terrific Elizabeth, you rock! (My guess is your desktop browser is logged
in to Facebook so it works now.)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Droidcon-Boston/conference-app-android/issues/22#issuecomment-292419799>,
or mute the thread

**Comment by emezias** [comment]
Andres' Facebook is set with strict permissions such that opening in an incognito window is a Facebook page not found. I'm going to leave it off because it looks like we, the app, set the wrong link.

**Comment by emezias** [comment]
The same is true for https://www.facebook.com/jsendros
It's just TOO ironic to leave that link alone since he works for Facebook. I don't think anybody but you is going to find this Easter egg. After all, it is that time of year.
